#!/bin/sh

set -e

ROOT=$(dirname $0)/..
SRC=${SRC:-"$ROOT/src"}
DST=${DST:-"$ROOT/public"}
HEADER=${HEADER:-"$SRC/header.html"}
FOOTER=${FOOTER:-"$SRC/footer.html"}
CSS=${CSS:-"/css/main.css"}
SRC_EXT=${SRC_EXT:-"md"}
DST_EXT=${DST_EXT:-"html"}
PANOPTS=${PANOPTS:-"--css $CSS --email-obfuscation=javascript --metadata-file=defaults.yml -f gfm -t html5 -B $HEADER -A $FOOTER"}

. $ROOT/tools/logging

mkdir -p $DST

status "Rendering"
for file in `find $SRC -name "*.$SRC_EXT" -type f`
do
   # Strip `src` path from file string
   FROM="${file##$SRC}"
   # Define a target file with the new extension
   TO="${FROM%%$SRC_EXT}$DST_EXT"
   echo "$FROM --> $TO"
   mkdir -p $(dirname "$DST$TO")
   pandoc $PANOPTS --output=$DST$TO $file || warn "failed TO create $TO"
done

status "Copying over assets"
for file in `find $SRC ! -name "*.$SRC_EXT" -type f`
do 
    FROM=$file
    TO="$DST${file##$SRC}"
    echo "${FROM##$ROOT} --> ${TO##$ROOT}"
    mkdir -p $(dirname $TO)
    cp $FROM $TO || warm "Failed TO copy asset $TO"
done
